import { RegionInfo } from "aws-cdk-lib/region-info";
import { RobotDirection } from "./baseTypes";

export interface Level {
  Id: string,
  NextId: string | null,
  Colors: string[],
  Items: string[],
  RobotRow: number,
  RobotCol: number,
  RobotDir: RobotDirection,
  AllowedCommands: number,
  DisallowSubs: boolean,
  DisallowColors: boolean,
  Title: string,
  About: string,
  SubLengths: number[],
  Tutorial: string[],
  ContentComment: string,
}


export const TUTORIAL_LEVELS: Level[] = [
  {
    Id: "-1",
    NextId: "-2",
    Colors: [
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
    ],
    Items: [
      "################",
      "################",
      "################",
      "#####.....######",
      "####.......#####",
      "####.*...*.#####",
      "####.......#####",
      "#####.....######",
      "################",
      "################",
      "################",
      "################",
    ],
    RobotRow: 5,
    RobotCol: 7,
    RobotDir: RobotDirection.Right,
    AllowedCommands: 0,
    DisallowSubs: true,
    DisallowColors: true,
    Title: "Tutorial: Part 1",
    About: "",
    SubLengths: [10, 0, 0, 0, 0],
    Tutorial: [
      '<b>Welcome to Robozzle!</b><br><br>Your task is to program a robot to pick up all stars in a level.',
      'In this puzzle, you get to use three commands: go straight, turn left, turn right (see bottom right).',
      'You will program the robot by placing the commands into the program slots (see bottom right).',
      'Now, go ahead and program the robot! When you think that your program will work, press the "Go!" button.'
    ],
    ContentComment: "HERE IDIOT",
  },
  {
    Id: "-2",
    NextId: "-3",
    Colors: [
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
    ],
    Items: [
      "################",
      "################",
      "################",
      "#####.....######",
      "####.......#####",
      "####.*...*.#####",
      "####.......#####",
      "#####.....######",
      "################",
      "################",
      "################",
      "################",
    ],
    RobotRow: 5,
    RobotCol: 7,
    RobotDir: RobotDirection.Right,
    AllowedCommands: 0,
    DisallowSubs: false,
    DisallowColors: true,
    Title: "Tutorial: Part 2",
    About: "",
    SubLengths: [5, 2, 0, 0, 0],
    Tutorial: [
      'In this puzzle, you have command slots available for a helper subroutine F2 (see bottom right).',
      'When you use the F2 command, the robot will execute the commands from the F2 slots.',
      'In this puzzle, you\'ll want to put two "go straight" commands into F2. Then, any time you use the F2 command, the robot will go forward twice. See if you can solve it.'
    ],
    ContentComment: "HERE IDIOT",
  }, {
    Id: "-3",
    NextId: "-4",
    Colors: [
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
    ],
    Items: [
      "################",
      "################",
      "################",
      "################",
      "###..........###",
      "###.********.###",
      "###..........###",
      "################",
      "################",
      "################",
      "################",
      "################"
    ],
    RobotRow: 5,
    RobotCol: 3,
    RobotDir: RobotDirection.Right,
    AllowedCommands: 0,
    DisallowSubs: false,
    DisallowColors: true,
    Title: "Tutorial: Part 3",
    About: "",
    SubLengths: [2, 0, 0, 0, 0],
    Tutorial: [
      'See if you can figure out how to solve this puzzle. You need to use the F1 command.'
    ],
    ContentComment: "HERE IDIOT",
  }, {
    Id: "-4",
    NextId: null,
    Colors: [
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRBRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRR",
    ],
    Items: [
      "################",
      "################",
      "####.*******####",
      "###########*####",
      "###########*####",
      "###########*####",
      "###########*####",
      "###########*####",
      "###########*####",
      "################",
      "################",
      "################"
    ],
    RobotRow: 2,
    RobotCol: 4,
    RobotDir: RobotDirection.Right,
    AllowedCommands: 0,
    DisallowSubs: false,
    DisallowColors: false,
    Title: "Tutorial: Part 4",
    About: "",
    SubLengths: [3, 0, 0, 0, 0],
    Tutorial: [
      'Let\'s make things even more interesting. You can mark a command with a particular color, and then the command will be skipped if the robot stands on a tile with a different color.',
      'For example, a blue right turn command will cause the robot to turn right if it is on a blue tile, but it will be skipped if the robot is on a green or a red tile.',
      'In this puzzle, you need to combine a blue right turn with the trick you saw in the previous puzzle. Go for it!'
    ],
    ContentComment: "HERE IDIOT",
  }
];



export function isTutorialLevel(id: string): boolean {
  return parseInt(id) < 0;
};


export function getDefaultLevel(): Level {
  return {
    Colors: [
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBBBB",
    ],
    Items: [
      "################",
      "################",
      "################",
      "################",
      "################",
      "#######..#######",
      "#######.*#######",
      "################",
      "################",
      "################",
      "################",
      "################",
    ],
    RobotDir: 0,
    RobotCol: 7,
    RobotRow: 6,
    AllowedCommands: 0,
    SubLengths: [10, 0, 0, 0, 0],
    Title: '',
    About: '',
  }
}
